# >> alacritty.yml



# >> Imports

[general]
import = ["/Users/osm/.config/alacritty/kanagawa_theme.toml"]



# >> Debugging

# NOTE: You can log to a known location by doing the following:
# ```sh
# cd /Applications/Alacritty.app/Contents/MacOS
# mv alacritty alacritty_executable
# echo -e "#!/bin/bash\n/Applications/Alacritty.app/Contents/MacOS/alacritty_executable > /tmp/alog.txt 2>&1" > alacritty
# chmod +x
# ```
#
# With the above you can now find the logs in /tmp/alog.txt
# To revert:
# ```sh
# cd /Applications/Alacritty.app/Contents/MacOS
# mv alacritty_executable alacritty
# ```

#[debug]
#persistent_logging = true



# >> Font configuration

[font]
size = 17.0

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0



# >> Shell

[terminal.shell]
program = "zsh"
args = [
  "--login",
  "-c", "exec fish"
]



# >> Env

[env]
TERM = "xterm-256color"



# >> Key bindings

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"


[terminal]
